function [Fx,Fy,Mz,Fx_max,Fy_max] = TireForcePac2002(Fz,kap,alp,camb,Pac)

eps_ = eps;

%% Reference load
Fz0 = Pac.F_z0_pac * Pac.LFZ0;
dfz = (Fz - Fz0) ./ Fz0;

%% ===========================
% Longitudinal Force (Pure Slip)
% ============================
camb_x = camb .* Pac.LGAX;

SHx = (Pac.p_Hx1 + Pac.p_Hx2 .* dfz) .* Pac.LHX;
SVx = Fz .* (Pac.p_Vx1 + Pac.p_Vx2 .* dfz) .* Pac.LVX .* Pac.LMUX;

kap_x = kap + SHx;

mu_x = (Pac.p_Dx1 + Pac.p_Dx2 .* dfz) .* ...
       (1 - Pac.p_Dx3 .* camb_x.^2) .* Pac.LMUX;

Dx = mu_x .* Fz;

Kxx = Fz .* (Pac.p_Kx1 + Pac.p_Kx2 .* dfz) .* ...
      exp(Pac.p_Kx3 .* dfz) .* Pac.LKX;

Cx = Pac.p_Cx1 * Pac.LCX;

Bx = Kxx ./ (Cx .* Dx + eps_);

Ex = (Pac.p_Ex1 + Pac.p_Ex2 .* dfz + Pac.p_Ex3 .* dfz.^2) .* ...
     (1 - Pac.p_Ex4 .* sign(kap_x)) .* Pac.LEX;

Fx0 = Dx .* sin( ...
      Cx .* atan( ...
      Bx .* kap_x - Ex .* (Bx .* kap_x - atan(Bx .* kap_x)) )) ...
      + SVx;

Fx_max = abs(Dx) + abs(SVx);

%% ===========================
% Lateral Force (Pure Slip)
% ============================
camb_y = camb .* Pac.LGAY;

SHy = (Pac.p_Hy1 + Pac.p_Hy2 .* dfz) .* Pac.LHY + ...
      Pac.p_Hy3 .* camb_y;

SVy = Fz .* ( ...
      (Pac.p_Vy1 + Pac.p_Vy2 .* dfz) .* Pac.LVY + ...
      (Pac.p_Vy3 + Pac.p_Vy4 .* dfz) .* camb_y ) ...
      .* Pac.LMUY;

alp_y = alp + SHy;

mu_y = (Pac.p_Dy1 + Pac.p_Dy2 .* dfz) .* ...
       (1 - Pac.p_Dy3 .* camb_y.^2) .* Pac.LMUY;

Dy = mu_y .* Fz;

Kya = Pac.p_Ky1 .* Fz0 .* ...
      sin(2 .* atan(Fz ./ (Pac.p_Ky2 .* Fz0))) .* ...
      (1 - Pac.p_Ky3 .* abs(camb_y)) .* Pac.LKY;

Cy = Pac.p_Cy1 * Pac.LCY;

By = Kya ./ (Cy .* Dy + eps_);

Ey = (Pac.p_Ey1 + Pac.p_Ey2 .* dfz) .* ...
     (1 - (Pac.p_Ey3 + Pac.p_Ey4 .* camb_y) .* sign(alp_y)) .* ...
     Pac.LEY;

Fy0 = Dy .* sin( ...
      Cy .* atan( ...
      By .* alp_y - Ey .* (By .* alp_y - atan(By .* alp_y)) )) ...
      + SVy;

Fy_max = abs(Dy) + abs(SVy);

%% =====================================
% Longitudinal Force (Combined Slip)
% =====================================
SHxa = Pac.r_Hx1;
Cxa  = Pac.r_Cx1;

Bxa = Pac.r_Bx1 .* cos(atan(Pac.r_Bx2 .* kap)) .* Pac.LXAL;
Exa = Pac.r_Ex1 + Pac.r_Ex2 .* dfz;

Dxa = Fx0 ./ ...
      cos(Cxa .* atan( ...
      Bxa .* SHxa - Exa .* ...
      (Bxa .* SHxa - atan(Bxa .* SHxa))));

Fx = Dxa .* cos( ...
     Cxa .* atan( ...
     Bxa .* (alp + SHxa) - ...
     Exa .* (Bxa .* (alp + SHxa) - atan(Bxa .* (alp + SHxa))) ));

%% =====================================
% Lateral Force (Combined Slip)
% =====================================
SHyk = Pac.r_Hy1 + Pac.r_Hy2 .* dfz;

Cyk = Pac.r_Cy1;

Byk = Pac.r_By1 .* ...
      cos(atan(Pac.r_By2 .* (alp - Pac.r_By3))) .* ...
      Pac.LYKA;

Eyk = Pac.r_Ey1 + Pac.r_Ey2 .* dfz;

Dyk = Fy0 ./ ...
      cos(Cyk .* atan( ...
      Byk .* SHyk - Eyk .* ...
      (Byk .* SHyk - atan(Byk .* SHyk))));

DVyk = mu_y .* Fz .* ...
       (Pac.r_Vy1 + Pac.r_Vy2 .* dfz + Pac.r_Vy3 .* camb) .* ...
       cos(atan(Pac.r_Vy4 .* alp));

SVyk = DVyk .* ...
       sin(Pac.r_Vy5 .* atan(Pac.r_Vy6 .* kap)) .* ...
       Pac.LVYKA;

Fy = Dyk .* cos( ...
     Cyk .* atan( ...
     Byk .* (kap + SHyk) - ...
     Eyk .* (Byk .* (kap + SHyk) - atan(Byk .* (kap + SHyk))) )) ...
     + SVyk;

%% ===========================
% Aligning Torque
% ============================
camb_z = camb .* Pac.LGAZ;

SHf = SHy + SVy ./ (Kya + eps_);

SHt = Pac.q_Hz1 + Pac.q_Hz2 .* dfz + ...
      (Pac.q_Hz3 + Pac.q_Hz4 .* dfz) .* camb_z;

alp_t = alp + SHt;
alp_r = alp + SHf;

Dr = Fz .* ( ...
     (Pac.q_Dz6 + Pac.q_Dz7 .* dfz) .* Pac.LRES + ...
     (Pac.q_Dz8 + Pac.q_Dz9 .* dfz) .* camb_z ) .* ...
     Pac.R_0 .* Pac.LMUY;

Br = Pac.q_Bz9 .* Pac.LKY ./ Pac.LMUY + ...
     Pac.q_Bz10 .* By .* Cy;

Bt = (Pac.q_Bz1 + Pac.q_Bz2 .* dfz + Pac.q_Bz3 .* dfz.^2) .* ...
     (1 + Pac.q_Bz4 .* camb_z + Pac.q_Bz5 .* abs(camb_z)) .* ...
     Pac.LKY ./ Pac.LMUY;

Ct = Pac.q_Cz1;

Dt = Fz .* (Pac.q_Dz1 + Pac.q_Dz2 .* dfz) .* ...
     (1 + Pac.q_Dz3 .* camb_z + Pac.q_Dz4 .* camb_z.^2) .* ...
     Pac.R_0 ./ Fz0 .* Pac.LTR;

Et = (Pac.q_Ez1 + Pac.q_Ez2 .* dfz + Pac.q_Ez3 .* dfz.^2) .* ...
     (1 + (Pac.q_Ez4 + Pac.q_Ez5 .* camb_z) .* ...
     2/pi .* atan(Bt .* Ct .* alp_t));

%% Combined-slip aligning torque
s = (Pac.s_sz1 + ...
     Pac.s_sz2 .* (Fy ./ Fz0) + ...
     (Pac.s_sz3 + Pac.s_sz4 .* dfz) .* camb) .* ...
     Pac.R_0 .* Pac.LS;

alp_teq = atan( ...
          sqrt( tan(alp_t).^2 + ...
          (Kxx ./ (Kya + eps_)).^2 .* kap.^2 ) ...
          .* sign(alp_t));

alp_req = atan( ...
          sqrt( tan(alp_r).^2 + ...
          (Kxx ./ (Kya + eps_)).^2 .* kap.^2 ) ...
          .* sign(alp_r));

Mzr = Dr .* cos(atan(Br .* alp_req)) .* cos(alp);

t = Dt .* cos( ...
    Ct .* atan( ...
    Bt .* alp_teq - ...
    Et .* (Bt .* alp_teq - atan(Bt .* alp_teq)) )) ...
    .* cos(alp);

Fy_ = Fy - SVyk;

Mz = -t .* Fy_ + Mzr + s .* Fx;

end