std_msgs/Header header

int8 cpu_usage_percent      # CPU usage across all cores in percent
int32 cpu_max_core_temp     # Maximum temperature across all cores in °C
int32 cpu_frequency         # Current CPU frequency in MHz
int8 ram_usage_percent      # RAM usage in percent
int32 disk_read_mbps        # Current disk reads in MB/s
int32 disk_write_mbps       # Current disk writes in MB/s
int32 disk_free_gb          # Current free space at / in GB